Implement JSG_DETACHED_METHOD and JSG_DETACHED_METHOD_NAMED
These new macros allow defining instance methods on JSG objects that
can be detached from the object using destructuring assignment, etc.
They fill an existing gap between JSG_METHOD and JSG_STATIC_METHOD.

```cpp
struct Foo : public jsg::Object {
  static void foo() {};
  void bar() {}
  static void baz() {}

  JSG_RESOURCE_TYPE(Foo) {
    JSG_DETACHED_METHOD(foo);
    JSG_METHOD(bar);
    JSG_STATIC_METHOD(baz);
  }
};
```

```js
const obj = new Foo();

// The bar method can only be called attached or bound to the Foo
obj.bar();  // Ok!

const { bar } = obj;

bar.call(obj); // Ok!
bar.apply(obj); // Ok!
bar.bind(obj)(); // Ok!
bar(); // Error: illegal invocation!

// The baz method is only defined statically on the Foo class
Foo.baz();  // Ok!
obj.baz(); // Error! baz is not a function

// Since foo is defined as a detached method, it can be called
// with or without the object as the receiver

obj.foo(); // Ok!
const { foo } = obj;
foo(); // Ok!

foo.call(obj); // Ok!
foo.call(null); // Ok!
foo.apply(obj); // Ok!
foo.apply(null); // Ok!
```

There is a bit of complexity if the implementation of `foo()` does
in fact need to know if there is a `this` bound to it. In that case
the current only solution is to define the method signature of `foo()`
as accepting a `const v8::FunctionCallBackInfo<v8::Value>&` as the
first argument, which allows the implementation to check and unwrap
the `this` object if it is bound. We can potentially simplify that
a bit. See the included jsg-test for an example of how to do this and
some discussion around how to simplify.