fix devcontainer setup on aarch64 macos
Without this patch, if I open the project in a devcontainer from macos, I get
the following error from clangd, and broken go-to-definition etc:

```
In included file: 'bits/wordsize.h' file not foundclang(pp_file_not_found)
features-time64.h(20, 10): Error occurred here
sqlite.h
/workspaces/workerd/src/workerd/util/sqlite.h
```

The problem is that `FROM mcr.microsoft.com/vscode/devcontainers/base:dev-bookworm`
brings in an aarch64 ("arm64") debian base image by default on arm macos. This
provides `/usr/include/aarch64-linux-gnu` instead of `/usr/include/x86_64-linux-gnu`.

I have put aarch64 lower down on the include path than x86_64, just in case someone
on desktop linux has some crazy multiarch/cross compilation setup going on.